# Docker version
version: '3'
services:
  # MySQL database
  mysql_environment:
    container_name: mysql
    image: mysql:5.7
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql/conf:/etc/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/backup:/data_backup/data
